# Generated by Django 5.0.7 on 2024-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTSPStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.CharField(max_length=255)),
                ('output_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
